---

- name: Deploy Grafana Container
  docker_container:
    image: grafana/grafana:7.5.5
    name: grafana
    restart_policy: always
    state: started
    recreate: yes
    ports:
      - 3000:3000
    volumes:
      - /opt/grafana:/var/lib/grafana:rw
      - /opt/grafana/plugins:/var/lib/grafana/plugins:rw
    env:
      TZ: America/Fortaleza
    command: grafana-cli plugins install alexanderzobnin-zabbix-app

