---
- name: Deploy PostgreSQL Container
  docker_container:
    image: postgres:12-alpine
    name: postgresql-zabbix
    restart_policy: always
    state: started
    volumes:
      - /opt/pgsql:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env:
      TZ: America/Fortaleza
      POSTGRES_DB: "zabbix"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix"