---
- name: Deploy Zabbix Agent Container
  docker_container:
    image: zabbix/zabbix-agent:alpine-5.0.2
    name: zabbix-agent
    restart_policy: always
    state: started
    ports: 
      - 10050:10050
    volumes:
      - /opt/pgsql:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env:
      ZBX_HOSTNAME: server
      ZBX_SERVER_HOST: server