---
- name: Deploy Zabbix Server Container
  docker_container:
    image: zabbix/zabbix-server-pgsql:alpine-5.0.2
    name: zabbix-server
    restart_policy: always
    state: started
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
    ports:
      - 10051:10051
    env:
      TZ: America/Fortaleza
      DB_SERVER_HOST: postgresql-zabbix
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      ZBX_DEBUGLEVEL: '2'
      ZBX_CACHESIZE: '1G'
      ZBX_STARTPINGERS: '500'
    links:
      - postgresql-zabbix
      - zabbix-agent