---
- name: Check se nó ja tem arquivos de kubernetes
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubernetes_init_stat
  changed_when: false

- name: Executar join command
  command: "{{ hostvars[groups.master[0]].join_command.stdout }}"
  when: not kubernetes_init_stat.stat.exists