---
- name: Instalar pacotes necessários
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - dnsutils
    - net-tools
    - htop
    - telnet
    - apt-transport-https
    - wget

- name: Baixar Kubectl
  command: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

- name: Install kubectl
  command: sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
