---
all:
  vars:
    ambiente: gcp
    zabbix_server_ip_passive: 10.15.1.4
    vm_ip: "{{ lookup('file', '../../terraform/outputs/public_ip_vm_instance_monitoring-02.txt') }}"

  hosts:
    elk:
      ansible_host: "{{ vm_ip }}"
  
  children:
      elk-stask:
        hosts:
          elk: