---
- name: Instalar pacotes de dependencias
  package:
    name: lsb-release
    state: present

- name: Pegar versao do OS
  command: lsb_release -sc
  register: os_version
  changed_when: false

- name: Baixar arquivos .deb do zabbix
  get_url:
    url: "{{agent_ubuntu_url}}{{ os_version.stdout }}_all.deb"
    dest: /opt

- name: Adicionar repositorio APT
  command: "chdir=/opt dpkg -i zabbix-release_5.0-1+{{ os_version.stdout }}_all.deb"
