- name: Configurar hosts
  hosts: registry
  remote_user: root
  tags: configure
  roles:
    - role: ansible-role-configure-hosts-docker

- name: Configurar Agent Zabbix
  hosts: all
  remote_user: root
  tags: zabbix
  roles:
    - role: ansible-role-zabbix-agent-configure


- name: Configurar Registry
  hosts: registry
  remote_user: root
  tags: registry
  roles:
    - role: registry
