- name: Configurar hosts
  hosts: elk
  remote_user: root
  tags: configure
  roles:
    - role: ansible-role-configure-hosts-docker

- name: Configurar Agent Zabbix
  hosts: all
  remote_user: root
  tags: zabbix
  roles:
    - role: ansible-role-zabbix-agent-configure

- name: Configurar ELASTIC LOGSTASH KIBANA
  hosts: elk
  remote_user: root
  tags: elk
  roles:
    - role: elk
