---
- name: Configurar Host - Docker
  hosts: all
  remote_user: root
  tags: configure
  roles:
    - role: ansible-role-configure-hosts-docker

- name: Configurar Agent Zabbix
  hosts: all
  remote_user: root
  tags: zabbix
  roles:
    - role: ansible-role-zabbix-agent-configure
    
- name: Install K8s Packages
  hosts: all
  remote_user: root
  tags: packages
  roles:
    - role: kubernetes-common-packages

- name: Configure Master Node
  hosts: node_master_01
  remote_user: root
  tags: master
  roles:
    - role: kubernetes-master

- name: Configure Worker Node
  hosts: node_worker_01
  remote_user: root
  tags: worker
  roles:
    - role: kubernetes-worker

- name: Configure Dashboard
  hosts: node_master_01
  remote_user: root
  tags: dashboard
  roles:
    - role: kubernetes-dashboard

- name: Configure Ingress Controller
  hosts: node_master_01
  remote_user: root
  tags: ingress
  roles:
    - role: kubernetes-ingress
